services:
  app:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint:
      [
        "sh",
        "-c",
        "npm install && npx prisma migrate deploy && npx prisma db seed && npm run build && npm run dev -- --host 0.0.0.0",
      ]
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://prisma:prisma@db:5432/prisma
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
